# Generated by Django 6.0.4 on 2026-08-20 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KuratorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='kurator_photos/')),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('lesson_topic', models.CharField(blank=True, default='', max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurator_photos', to='academy.group')),
                ('kurator', models.ForeignKey(limit_choices_to={'role': 'kurator'}, on_delete=django.db.models.deletion.CASCADE, related_name='kurator_photos', to=settings.AUTH_USER_MODEL)),
                ('students_present', models.ManyToManyField(blank=True, related_name='photos_present', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='KuratorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report_text', models.TextField()),
                ('groups_covered', models.ManyToManyField(blank=True, related_name='kurator_reports', to='academy.group')),
                ('kurator', models.ForeignKey(limit_choices_to={'role': 'kurator'}, on_delete=django.db.models.deletion.CASCADE, related_name='kurator_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kurator Report',
                'verbose_name_plural': 'Kurator Reports',
                'ordering': ['-date'],
            },
        ),
    ]
